### ISSUE TITLE
Question about the dataset simulation name 

### ISSUE THREAD

**Issue by Gxinhu** [Extrality/airfrans_lib#3]
Hello, this dataset lib is quiet helpful.

But the simulation name makes me confuse.
For example, https://github.com/Extrality/airfrans_lib/blob/1e7823bc079c2e645a5f8e32179c014df529aec6/README.md?plain=1#L44 
According to your another code https://github.com/Extrality/NACA_simulation, the first digit `57.872`,and the second one `7.314` is the AOA. But the last three digits `5.454_3.799_13.179`, I only know it is represent a 4-digit NACA airfoil.

Could you please explain which arifoil of `5.454_3.799_13.179` reprensent. And on the contrary, how to represent NACA0112 by the above method.

**Comment by FlorentExtrality** [comment]
Hi!
I am so sorry to answer you that late...
So for the name, you are right, when `'airFoil2D_SST_57.872_7.314_5.454_3.799_13.179'` is given it means, SST turbulence model (SA for Spalart-Allmaras), 57.812 meters per second for the magnitude of the inlet velocity, 7.314 is the angle of attack, 5.454 is the first parameter of the airfoil, 3.799 the second and 13.179 the last. It is a NACA 4 digits in this case, it would have 4 parameters after the angle of attack for a 5 digits NACA (the last two digits are the thickness of the airfoil and it is given at a single parameter).

For example, a simulation with k-omega SST turbulence model, 30 meters per second, 10 degrees of angle of attack and for the NACA 0112 will give `'airFoil2D_SST_30_10_0_1_12'`. The only difference is that in the dataset, the digits are real numbers instead of integers as the parametrization of shapes in those families allows the extension to real numbers. It is maybe better to write the NACA 0112 in the form NACA (0, 1, 12) and with this form the above airfoil would be the NACA (5.454, 3.799, 13.179).

Best,
Florent

**Comment by Gxinhu** [comment]
Thank you so much to answer my question!

Previously, I thought the NACA number only could be integer, such as NACA 0012, not realize it could be float too.
